//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeChange.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAction
    {
        public System.Guid ID { get; set; }
        public System.Guid IDUser { get; set; }
        public System.Guid IDAction { get; set; }
        public Nullable<bool> Dosao { get; set; }
    
        public virtual Actions Actions { get; set; }
        public virtual Users Users { get; set; }
    }
}
